application: threedailythingsapp
version: 1
runtime: php
api_version: 1

handlers:
- url: /(.+)
  static_files: www/\1
  upload: www/(.+)

- url: /
  static_files: www/index.html
  upload: www/index.html
